name: Release Jbeam Edit extension

on:
  push:
    tags: [v*]

jobs:
  integration-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - run: npm clean-install
      - name: Check formatting with js-beautify
        run: |
          npm run format
          git diff --exit-code
      - run: npm run build
      - name: Package extension
        run: npx vsce package
      - name: Publish to Visual Studio Marketplace
        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }}
